name: Makefile CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: update
      run: ./scripts/feeds update -a
      
    - name: Install feeds
      run: ./scripts/feeds install -a
      
    - name: make
      run: make -j1 V=s
